name: Draintherain.com
favicon: null
layout_spectrum: 0.4720258
typography_spectrum: 0.7781956
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Seamless Rain Gutters
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#010101'
    - '#3c2e25'
    - '#a4afc1'
    - '#b31515'
  brandStrength: 0.0368753
  lightness: 0.4294502
  saturation: 0.5556514
  rhythmicContrast: 0.5
purpose: []
